import type { Implementation } from "../../types/implementation";

/** Datos de ejemplo hasta que exista la API (fase 0 → fase 1). */
export const SAMPLE_IMPLEMENTATIONS: Implementation[] = [
  {
    id: "imp-helpdesk-v2",
    number: "IMP-0001",
    title: "Helpdesk v2",
    client: "Seraph Systems",
    dueDate: "2026-12-18",
    stages: [
      {
        id: "s0",
        order: 0,
        name: "Fundaciones",
        status: "in_progress",
        side: "internal",
        estimateDays: 14,
        checklist: [
          { title: "Rama v2 en GitHub", status: "done" },
          { title: "PocketBase v2 vacío en pb-support.erpsys.pro", status: "done" },
          { title: "Respaldo de los datos del helpdesk v1", status: "done" },
          { title: "App web v2 publicada en support.erpsys.pro", status: "done" },
          { title: "Modo claro/oscuro y temas de color", status: "done" },
          { title: "Layout del frontend con la base visual de erpsys", status: "in_progress" },
          { title: "Idiomas español, inglés y portugués", status: "in_progress" },
          { title: "Docker Compose de una instancia (web, api, pocketbase; faltan worker y redis)", status: "in_progress" },
          { title: "Monorepo (apps/api, apps/web, packages)", status: "in_progress" },
          { title: "Esquema normalizado en PocketBase con migraciones (68 colecciones)", status: "done" },
          { title: "Hooks de integridad, numeración e historial automático", status: "done" },
          { title: "API en Node.js + TypeScript (config, routes, controllers, services, models, middlewares, validators, types, utils)", status: "done" },
          { title: "Login con JWT (Ed25519) y refresh token rotativo", status: "done" },
          { title: "Roles y permisos base", status: "done" },
          { title: "Pantalla de inicio de sesión y preferencias guardadas por usuario", status: "done" },
          { title: "CI con imágenes versionadas", status: "pending" },
        ],
      },
      {
        id: "s1",
        order: 1,
        name: "MVP",
        status: "pending",
        side: "internal",
        estimateDays: 49,
        summary: "Casos normalizados, soporte, implementaciones con etapas y requerimientos al cliente, portal, correos, API pública, dashboard y CLI de instancias.",
        checklist: [],
      },
      {
        id: "s2",
        order: 2,
        name: "v1.0 operación completa",
        status: "pending",
        side: "internal",
        estimateDays: 42,
        summary: "Integración con erpsyschat, correo entrante, SLA, widget y SSO, webhooks, consola de instancias.",
        checklist: [],
      },
      {
        id: "s3",
        order: 3,
        name: "Canales y experiencia",
        status: "pending",
        side: "internal",
        estimateDays: 35,
        summary: "Slack, Teams, Telegram, WhatsApp, base de conocimiento, encuestas, PWA.",
        checklist: [],
      },
      {
        id: "s4",
        order: 4,
        name: "Inteligencia",
        status: "pending",
        side: "internal",
        estimateDays: null,
        summary: "Clasificación sugerida, duplicados, resúmenes y predicción de retrasos.",
        checklist: [],
      },
      {
        id: "s5",
        order: 5,
        name: "Negocio y escala",
        status: "pending",
        side: "internal",
        estimateDays: null,
        summary: "Planes y facturación, autoservicio de alta, varias instancias por servidor, on-premise.",
        checklist: [],
      },
    ],
    requests: [
      { id: "r1", stageId: "s0", title: "Confirmar el lenguaje del backend (Node.js + TypeScript o Go)", status: "accepted", blocking: true, dueDate: "2026-10-07" },
      { id: "r2", stageId: "s1", title: "Proveedor de correo y remitente para los avisos", status: "pending", blocking: false, dueDate: "2026-10-30" },
    ],
    log: [
      { date: "2026-10-02", text: "API v2 en Node.js + TypeScript publicada en support.erpsys.pro/api: inicio de sesión con JWT, sesiones revocables, permisos por rol y mensajes en español, inglés y portugués. La app ya pide iniciar sesión." },
      { date: "2026-10-02", text: "Base de datos normalizada en pb-support.erpsys.pro: 68 colecciones relacionadas, datos de fábrica (flujos, tipos, plantilla de implementación con requerimientos al cliente) y reglas de integridad probadas." },
      { date: "2026-10-02", text: "La app web v2 ya se ve en support.erpsys.pro con la base visual de erpsys, idiomas y temas. La vista de implementación usa el diseño aprobado." },
      { date: "2026-10-02", text: "Se creó la rama v2, un PocketBase nuevo en pb-support.erpsys.pro y se respaldaron los datos del helpdesk v1." },
      { date: "2026-10-01", text: "Roadmap: modelo de datos normalizado, tipos de caso configurables y requerimientos al cliente." },
    ],
  },
  {
    id: "imp-cap-world",
    number: "IMP-0002",
    title: "Implementación ERPSYS",
    client: "Cap World (ejemplo)",
    dueDate: "2026-11-06",
    stages: [
      {
        id: "c1",
        order: 1,
        name: "Kickoff",
        status: "completed",
        side: "shared",
        estimateDays: 2,
        checklist: [
          { title: "Reunión de arranque", status: "done" },
          { title: "Plan de trabajo aprobado", status: "done" },
        ],
      },
      {
        id: "c2",
        order: 2,
        name: "Carga de información",
        status: "waiting_client",
        side: "client",
        estimateDays: 5,
        summary: "El cliente entrega catálogos y datos maestros con las plantillas enviadas.",
        checklist: [
          { title: "Enviar plantillas al cliente", status: "done" },
          { title: "Recibir catálogo de productos", status: "in_progress" },
          { title: "Recibir listado de clientes", status: "pending" },
          { title: "Validar datos recibidos", status: "pending" },
        ],
      },
      { id: "c3", order: 3, name: "Configuración", status: "pending", side: "internal", estimateDays: 7, summary: "Parametrización del ERP con los datos validados.", checklist: [] },
      { id: "c4", order: 4, name: "Capacitación", status: "pending", side: "shared", estimateDays: 3, summary: "Sesiones por área con los usuarios clave.", checklist: [] },
      { id: "c5", order: 5, name: "Pruebas", status: "pending", side: "shared", estimateDays: 5, summary: "Pruebas de punta a punta con el cliente.", checklist: [] },
      { id: "c6", order: 6, name: "Salida a producción", status: "pending", side: "internal", estimateDays: 1, summary: "Arranque y acompañamiento del primer día.", checklist: [] },
    ],
    requests: [
      { id: "q1", stageId: "c2", title: "Catálogo de productos (plantilla Excel)", status: "in_review", blocking: true, dueDate: "2026-10-03" },
      { id: "q2", stageId: "c2", title: "Listado de clientes con NIT", status: "pending", blocking: true, dueDate: "2026-10-05" },
      { id: "q3", stageId: "c2", title: "Acceso VPN al servidor", status: "accepted", blocking: false, dueDate: "2026-09-30" },
    ],
    log: [
      { date: "2026-10-01", text: "El cliente entregó el catálogo de productos; queda en revisión." },
      { date: "2026-09-29", text: "Se enviaron las plantillas de carga de información al cliente." },
      { date: "2026-09-28", text: "Kickoff completado y plan de trabajo aprobado." },
    ],
  },
];

export function findImplementation(id: string): Implementation | undefined {
  return SAMPLE_IMPLEMENTATIONS.find((i) => i.id === id);
}
